<?php

// Genero: ProgramasProgramacion.com
echo "var capture ={\n";
echo "	inNombre : \"Este campo está vacio\",\n";
echo "	inApellido : \"Este campo está vacio\",\n";
echo "	inTelefono : \"Este campo está vacio\",\n";
echo "	inMail : \"Este campo está vacio\",\n";
echo "	inText : \"Este campo está vacio\",\n";
echo "	valorizar () {\n";
echo "		this.inNombre = \$(\"#nombre\").val();\n";
echo "		this.inApellido = \$(\"#apellido\").val();\n";
echo "		this.inTelefono = \$(\"#tel\").val();\n";
echo "		this.inMail = \$(\"#mail\").val();\n";
echo "		this.inText = \$(\"#texto\").val();\n";
echo "	},\n";
echo "};\n";
echo "var primerNivel = {\n";
echo "	statusNombre: 0400,\n";
echo "	statusApellido: 0400,\n";
echo "	statusTelefono: 0400,\n";
echo "	statusMail: 0400,\n";
echo "	statusTexto: 0400,\n";
echo "\n";
echo "	funcNombre (){\n";
echo "		capture.valorizar();\n";
echo "		var objNombre = \$(\"#nombre\");\n";
echo "		var pNombre = \$(\"#pnomb\");\n";
echo "		var expresionNombre =/^[A-Za-z\\u00C0-\\u017F]*\$/;\n";
echo "		if (capture.inNombre===\"\") {\n";
echo "			objNombre.addClass(\"vacio\");\n";
echo "			pNombre.addClass(\"pvacio\").hide();\n";
echo "			this.statusNombre = 0400\n";
echo "		} else if(objNombre.val().length <= 3) {\n";
echo "			objNombre.addClass(\"corto\");\n";
echo "			pNombre.addClass(\"pcorto\").hide();\n";
echo "			this.statusNombre = 0400\n";
echo "		} else if(objNombre.val().length >= 15) {\n";
echo "			objNombre.addClass(\"largo\");\n";
echo "			pNombre.addClass(\"plargo\").hide();\n";
echo "			this.statusNombre = 0400\n";
echo "		} else if(!expresionNombre.test(capture.inNombre)) {\n";
echo "			objNombre.addClass(\"inex\");\n";
echo "			pNombre.addClass(\"pinex\").hide();\n";
echo "			this.statusNombre = 0400\n";
echo "		}else {\n";
echo "			objNombre.addClass(\"correct\");\n";
echo "			this.statusNombre = 1345\n";
echo "		}\n";
echo "	},\n";
echo "	funcApellido() {\n";
echo "		capture.valorizar();\n";
echo "		var objApellido = \$(\"#apellido\");\n";
echo "		var pApellido = \$(\"#papell\");\n";
echo "		var expresionApellido =/^[A-Za-z\\u00C0-\\u017F]*\$/;\n";
echo "		if (capture.inApellido===\"\") {\n";
echo "			objApellido.addClass(\"vacio\");\n";
echo "			pApellido.addClass(\"pvacio\").hide();\n";
echo "			this.statusApellido = 0400\n";
echo "		} else if(objApellido.val().length <= 3) {\n";
echo "			objApellido.addClass(\"corto\");\n";
echo "			pApellido.addClass(\"pcorto\").hide();\n";
echo "			this.statusApellido = 0400\n";
echo "		} else if(objApellido.val().length >= 15) {\n";
echo "			objApellido.addClass(\"largo\");\n";
echo "			pApellido.addClass(\"plargo\").hide();\n";
echo "			this.statusApellido = 0400\n";
echo "		} else if(!expresionApellido.test(capture.inApellido)) {\n";
echo "			objApellido.addClass(\"inex\");\n";
echo "			pApellido.addClass(\"pinex\").hide();\n";
echo "			this.statusApellido = 0400\n";
echo "		}else {\n";
echo "			objApellido.addClass(\"correct\");\n";
echo "			this.statusApellido = 1345\n";
echo "		}\n";
echo "	},\n";
echo "	funcTelefono() {\n";
echo "		capture.valorizar();\n";
echo "		var objTelefono = \$(\"#tel\");\n";
echo "		var pTelefono = \$(\"#ptel\");\n";
echo "		if (objTelefono.val().length == 0) {\n";
echo "			objTelefono.addClass(\"vacio\");\n";
echo "			pTelefono.addClass(\"pvacio\").hide();\n";
echo "			this.statusTelefono = 0400\n";
echo "		} else if(objTelefono.val().length <= 7) {\n";
echo "			objTelefono.addClass(\"corto\");\n";
echo "			pTelefono.addClass(\"pcorto\").hide();\n";
echo "			this.statusTelefono = 0400\n";
echo "		} else if(objTelefono.val().length >= 13) {\n";
echo "			objTelefono.addClass(\"largo\");\n";
echo "			pTelefono.addClass(\"plargo\").hide();\n";
echo "			this.statusTelefono = 0400\n";
echo "		} else if(isNaN(capture.inTelefono)) {\n";
echo "			objTelefono.addClass(\"inex\");\n";
echo "			pTelefono.addClass(\"pinex\").hide();\n";
echo "			this.statusTelefono = 0400\n";
echo "		}else {\n";
echo "			objTelefono.addClass(\"correct\");\n";
echo "			this.statusTelefono = 1345\n";
echo "		}\n";
echo "	},\n";
echo "	funcMail() {\n";
echo "		capture.valorizar();\n";
echo "		var objMail = \$(\"#mail\");\n";
echo "		var pMail = \$(\"#pmail\");\n";
echo "		var expresionMail =/\\w+@\\w+\\.+[a-z]/;\n";
echo "		if (capture.inMail == \"\") {\n";
echo "			objMail.addClass(\"vacio\");\n";
echo "			pMail.addClass(\"pvacio\").hide();\n";
echo "			this.statusMail = 0400\n";
echo "		} else if(objMail.val().length <= 9) {\n";
echo "			objMail.addClass(\"corto\");\n";
echo "			pMail.addClass(\"pcorto\").hide();\n";
echo "			this.statusMail = 0400\n";
echo "		} else if(objMail.val().length >= 25) {\n";
echo "			objMail.addClass(\"largo\");\n";
echo "			pMail.addClass(\"plargo\").hide();\n";
echo "			this.statusMail = 0400\n";
echo "		} else if(!expresionMail.test(capture.inMail)) {\n";
echo "			objMail.addClass(\"inex\");\n";
echo "			pMail.addClass(\"pinex\").hide();\n";
echo "			this.statusMail = 0400\n";
echo "		}else {\n";
echo "			objMail.addClass(\"correct\");\n";
echo "			this.statusMail = 1345\n";
echo "		}\n";
echo "	},\n";
echo "	funcText() {\n";
echo "		capture.valorizar();\n";
echo "		var objText = \$(\"#texto\");\n";
echo "		var pText = \$(\"#parea\");\n";
echo "		var expresionText =/^[A-Za-z0-9\\\$\"\\s\\-\\.\\u00C0-\\u017F]*\$/;\n";
echo "		if (capture.inText === \"\") {\n";
echo "			objText.addClass(\"vacio\");\n";
echo "			pText.addClass(\"pvacio\").hide();\n";
echo "			this.statusTexto = 0400\n";
echo "		} else if(objText.val().length <= 10) {\n";
echo "			objText.addClass(\"corto\");\n";
echo "			pText.addClass(\"pcorto\").hide();\n";
echo "			this.statusTexto = 0400\n";
echo "		} else if(!expresionText.test(capture.inText)) {\n";
echo "			objText.addClass(\"inex\");\n";
echo "			pText.addClass(\"pinex\").hide();\n";
echo "			this.statusTexto = 0400\n";
echo "		}else {\n";
echo "			objText.addClass(\"correct\");\n";
echo "			this.statusTexto = 1345\n";
echo "		}\n";
echo "	},\n";
echo "	funcParrafos() {\n";
echo "		\$(\".pvacio\").text(\"Este contenedor está vacio\").slideDown(500);\n";
echo "		\$(\".pinex\").text(\"Formato erroneo\").slideDown(500);\n";
echo "		\$(\".pcorto\").text(\"Este texto es muy corto\").slideDown(500);\n";
echo "		\$(\".plargo\").text(\"Se exedio el maximo de caracteres\").slideDown(500);\n";
echo "	},\n";
echo "	funcValidar(){\n";
echo "		var sectores = \$(\".sector\");\n";
echo "		var parrafos = \$(\".pstatus\");\n";
echo "		parrafos.slideUp(500, function(){\n";
echo "			\$().empty()\n";
echo "		});\n";
echo "		sectores.removeClass(\"vacio\").removeClass(\"corto\").removeClass(\"largo\").removeClass(\".inex\").removeClass(\"correct\");\n";
echo "		parrafos.removeClass(\"pvacio\").removeClass(\"pcorto\").removeClass(\"plargo\").removeClass(\"pinex\");\n";
echo "		this.funcNombre();\n";
echo "		this.funcApellido();\n";
echo "		this.funcTelefono();\n";
echo "		this.funcMail();\n";
echo "		this.funcText();\n";
echo "		this.funcParrafos();\n";
echo "	}\n";
echo "};\n";
echo "\n";
echo "var SegundoNivel = {\n";
echo "	valorSegundoNivel: false,\n";
echo "	funcSegundoNivel (){\n";
echo "		primerNivel.funcValidar();\n";
echo "		if (primerNivel.statusNombre === 1345 && primerNivel.statusApellido === 1345 && primerNivel.statusTelefono === 1345 && primerNivel.statusMail === 1345 && primerNivel.statusTexto === 1345) {\n";
echo "			this.valorSegundoNivel = true\n";
echo "		} else {\n";
echo "			this.valorSegundoNivel = false\n";
echo "		}\n";
echo "	}\n";
echo "}\n";
echo "\n";
echo "/*-------------------------------------------*/\n";
echo "function confirmar() {\n";
echo "	capture.valorizar();\n";
echo "	console.log(SegundoNivel.valorSegundoNivel);\n";
echo "	SegundoNivel.funcSegundoNivel();\n";
echo "	console.log(SegundoNivel.valorSegundoNivel);\n";
echo "	\$(\"\").text(\"Hole\")\n";
echo "	return SegundoNivel.valorSegundoNivel\n";
echo "}\n";

?>